services:
  backend:
    build: ./backend
    container_name: bitcoin-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: bitcoin-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
